"""empty message

Revision ID: af551fc90a1c
Revises: ff9562388142
Create Date: 2023-01-28 20:59:58.457028

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'af551fc90a1c'
down_revision = 'ff9562388142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('checkout_session_id', sa.String(), nullable=True))
    # ### end Alembic commands ###

    if environment == "production":
        op.execute(f"ALTER TABLE carts SET SCHEMA {SCHEMA};")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'checkout_session_id')
    # ### end Alembic commands ###